### ISSUE TITLE
refactor#36 - [회원, 부서 , 직급] request, response 간소화 작업

### ISSUE THREAD

**Issue by wintersky2** [TheBestofBest/FinalProj_BusinessBridge#36]
### 구현필요사항 or 이슈내역
- 회원, 부서, 직급 도메인의 request, response 클래스 간소화 작업입니다.
- 예) PostGradeRequest, PatchGradeRequest  --> GradeRequest 클래스로 통일 후 내부에 PostGradeRequest, PatchGradeRequest 클래스 구현

### ToDo
- [x] 부서 간소화

- [x] 부서 컨트롤러 수정

- [x] 직급 간소화

- [x] 직급 컨트롤러 수정
 
- [x] 회원 간소화

- [x] 회원 컨트롤러 수정

### 특이사항, 변경내역 ~~(없을 경우 삭제)~~
- etc 1
- etc 2
