### ISSUE TITLE
Feature#38 - [Request, Response] 생성

### ISSUE THREAD

**Issue by DooHwanKim92** [TheBestofBest/FinalProj_BusinessBridge#38]
### 구현필요사항 or 이슈내역
- Rebate, WorkingState, Statistics → Request, Response 필요

### ToDo
- [x] Rebate Request, Response
- [x] WorkingState Request, Response
- [x] Statistics Request, Response

**Comment by DooHwanKim92** [comment]
정산, 근태, 통계 등은 `Request`가 필요하지 않은 기능들로 판단되어 `Response`만 생성함
응답할 데이터는 추후 디테일하게 구현 예정
