### ISSUE TITLE
Refactor#64 - [회원, 직급, 부서] 생성 유효성 검증, 엔티티 속성 추가, 메서드 수정

### ISSUE THREAD

**Issue by wintersky2** [TheBestofBest/FinalProj_BusinessBridge#64]
### 구현필요사항 or 이슈내역
- 각 엔티티 생성시 중복, 기타 유효성 검증이 필요합니다.
- Member 엔티티에 속성 추가.
- 유효성 검증, 코드 가독성 상승을 위한 작업 추가.

### ToDo

- [x] Member 엔티티 속성 추가
- 내선번호 (String)
- 개인연락처 (String)
- 담당업무 (String)
- 상태 메세지 (Status Messege)
- 프로필 사진 (ProfileImg)
- 상태 ( 온라인, 오프라인, 부재중 )

- [x] department 엔티티 생성 시 ,수정 시 중복 유효성 검증
- [x] grade 엔티티 생성 시 ,수정 시 중복 유효성 검증
- [x] member 엔티티 생성 시 ,수정 시 중복 유효성 검증
- [x] DepartmentService, GradeService에 FindByCode 메서드  필요

### 특이사항, 변경내역 
- 백 엔드  member/ApiV1MembersController 에 getMapping members/me 추가 했습니다.
- 프론트 엔드에 components/Api/MeApiWithReactQuery 로 페이지 새로고침 시에 캐싱된 query 데이터가 날아가지 않게 했습니다.
